# Automating Resource Management
Often, your application works with files, databases, and various connection objects. 
Commonly, these external data sources are referred to as _resources_. In many cases, you _open_
a connection to the resource, whether it’s over the network or within a file system. You
then _read_/_write_ the data you want. Finally, you close the resource to indicate that you are
done with it. <br />

&emsp;&emsp;
What happens if you don’t close a resource when you are done with it? In short, a lot
of bad things could happen. If you are connecting to a database, you could use up all
available connections, meaning no one can talk to the database until you release your 
connections. Although you commonly hear about memory leaks causing programs to fail, a
_resource leak_ is just as bad and occurs when a program fails to release its connections to a
resource, resulting in the resource becoming inaccessible. This could mean your program
can no longer talk to the database—or, even worse, all programs are unable to reach
the database! <br />

&emsp;&emsp;
For the exam, a _resource_ is typically a file or database that requires some kind of stream
or connection to read or write data. In Chapter 14 and Chapter 15, you create numerous
resources that will need to be closed when you are finished with them.

## I. Introducing Try-with-Resources
Let’s take a look at a method that opens a file, reads the data, and closes it:

```java
4:  public void readFile(String file) {
5:      FileInputStream is = null;
6:      try {
7:          is = new FileInputStream("myfile.txt");
8:          // Read file data
9:      } catch (IOException e) {
10:         e.printStackTrace();
11:     } finally {
12:         if (is != null) {
13:             try {
14:                 is.close();
15:             } catch (IOException e2) {
16:                 e2.printStackTrace();
17:             }
18:         }
19:     }
20: }
```

&emsp;&emsp;
Wow, that’s a long method! Why do we have two **try** and **catch** blocks? Well, lines
7 and 14 both include checked **IOException** calls, and those need to be caught in the
method or rethrown by the method. Half the lines of code in this method are just 
closing a resource. And the more resources you have, the longer code like this becomes. For
example, you may have multiple resources that need to be closed in a particular order.
You also don’t want an exception caused by closing one resource to prevent the closing of
another resource. <br />

&emsp;&emsp;
To solve this, Java includes the _try-with-resources_ statement to automatically close
all resources opened in a **try** clause. This feature is also known as _automatic resource
management_, because Java automatically takes care of the closing. <br />

&emsp;&emsp;
Let’s take a look at our same example using a try-with-resources statement:

```java
4:  public void readFile(String file) {
5:      try (FileInputStream is = new FileInputStream("myfile.txt")) {
6:          // Read file data
7:      } catch (IOException e) {
8:          e.printStackTrace();
9:      }
10: }
```

&emsp;&emsp;
Functionally, they are similar, but our new version has half as many lines. More 
importantly, though, by using a try-with-resources statement, we guarantee that as soon as a 
connection passes out of scope, Java will attempt to close it within the same method. <br />

&emsp;&emsp;
Behind the scenes, the compiler replaces a try-with-resources block with a **try** and **finally**
block. We refer to this “hidden” **finally** block as an _implicit_ **finally** block since it is created
and used by the compiler automatically. You can still create a programmer-defined **finally**
block when using a try-with-resources statement; just be aware that the implicit one will be
called first.

> #### Tip
> Unlike garbage collection, resources are not automatically closed when
they go out of scope. Therefore, it is recommended that you close
resources in the same block of code that opens them. By using a try-with-resources
statement to open all your resources, this happens automatically

## II. Basics of Try-with-Resources
Figure 11.5 shows what a try-with-resources statement looks like. Notice that one or more
resources can be opened in the **try** clause. When multiple resources are opened, they are
closed in the _reverse_ of the order in which they were created. Also, notice that parentheses
are used to list those resources, and semicolons are used to separate the declarations. This
works just like declaring multiple indexes in a **for** loop.

> **Figure 11.5** The syntax of a basic try-with-resources statement

<img src="https://github.com/khoahd7621/oracle-certified-professional-java-se-17-practice/blob/main/images/chapter11/unit4/figure11.5.png" alt="Figure 11.5" width="700" />

&emsp;&emsp;
What happened to the **catch** block in Figure 11.5? Well, it turns out a **catch** block
is optional with a try-with-resources statement. For example, we can rewrite the previous
`readFile()` example so that the method declares the exception to make it even shorter:

```java
4:  public void readFile(String file) throws IOException {
5:      try (FileInputStream is = new FileInputStream("myfile.txt")) {
6:          // Read file data
7:      }
8:  }
```

&emsp;&emsp;
Earlier in the chapter, you learned that a **try** statement must have one or more **catch**
blocks or a **finally** block. A try-with-resources statement differs from a **try** statement in
that neither of these is required, although a developer may add both. For the exam, you need
to know that the implicit **finally** block runs _before_ any programmer-coded ones.

### &emsp;&emsp; A. Constructing Try-with-Resources Statements

Only classes that implement the **AutoCloseable** interface can be used in a try-with-resources
statement. For example, the following does not compile as **String** does not implement the
**AutoCloseable** interface:

```java
try (String reptile = "lizard") {}
```

&emsp;&emsp;
Inheriting **AutoCloseable** requires implementing a compatible `close()` method.

```java
interface AutoCloseable {
    public void close() throws Exception;
}
```

&emsp;&emsp;
From your studies of method overriding, this means that the implemented version of
`close()` can choose to throw **Exception** or a subclass or not throw any exceptions at all. <br />

&emsp;&emsp;
Throughout the rest of this section, we use the following custom resource class that
simply prints a message when the `close()` method is called:

```java
public class MyFileClass implements AutoCloseable {
    private final int num;
    
    public MyFileClass(int num) { this.num = num; }
    
    @Override public void close() {
        System.out.println("Closing: " + num);
    }
}
```

> #### Note
> In Chapter 14, you encounter resources that implement
**Closeable** rather than **AutoCloseable**. Since **Closeable** extends
**AutoCloseable**, they are both supported in try-with-resources 
statements. The only difference between the two is that **Closeable**’s
`close()` method declares **IOException**, while **AutoCloseable**’s
`close()` method declares **Exception**.

### &emsp;&emsp; B. Declaring Resources
While try-with-resources does support declaring multiple variables, each variable must be
declared in a separate statement. For example, the following do not compile:

```java
try (MyFileClass is = new MyFileClass(1), // DOES NOT COMPILE
    os = new MyFileClass(2)) {
}

try (MyFileClass ab = new MyFileClass(1), // DOES NOT COMPILE
    MyFileClass cd = new MyFileClass(2)) {
}
```

&emsp;&emsp;
The first example does not compile because it is missing the data type, and it uses a
comma `,` instead of a semicolon `;`. The second example does not compile because it also
uses a comma `,` instead of a semicolon `;`. Each resource must include the data type and
be separated by a semicolon `;`. <br />

&emsp;&emsp;
You can declare a resource using **var** as the data type in a try-with-resources statement,
since resources are local variables.

```java
try (var f = new BufferedInputStream(new FileInputStream("it.txt"))) {
    // Process file
}
```

&emsp;&emsp;
Declaring resources is a common situation where using **var** is quite helpful, as it shortens
the already long line of code.

### &emsp;&emsp; C. Scope of Try-with-Resources
The resources created in the **try** clause are in scope only within the **try** block. This is another
way to remember that the implicit **finally** runs before any **catch**/**finally** blocks that you code
yourself. The implicit close has run already, and the resource is no longer available. Do you
see why lines 6 and 8 don’t compile in this example?

```java
3:  try (Scanner s = new Scanner(System.in)) {
4:      s.nextLine();
5:  } catch(Exception e) {
6:      s.nextInt(); // DOES NOT COMPILE
7:  } finally {
8:      s.nextInt(); // DOES NOT COMPILE
9:  }
```

&emsp;&emsp;
The problem is that **Scanner** has gone out of scope at the end of the **try** clause. Lines 6
and 8 do not have access to it. This is a nice feature. You can’t accidentally use an object that
has been closed. In a traditional **try** statement, the variable has to be declared before the try
statement so that both the **try** and **finally** blocks can access it, which has the unpleasant
side effect of making the variable in scope for the rest of the method, just inviting you to call it
by accident.

### &emsp;&emsp; D. Following Order of Operations
When working with try-with-resources statements, it is important to know that resources
are closed in the reverse of the order in which they are created. Using our custom **MyFileClass**,
can you figure out what this method prints?

```java
public static void main(String... xyz) {
    try (MyFileClass bookReader = new MyFileClass(1);
            MyFileClass movieReader = new MyFileClass(2)) {
        System.out.println("Try Block");
        throw new RuntimeException();
    } catch (Exception e) {
        System.out.println("Catch Block");
    } finally {
        System.out.println("Finally Block");
    }
}
```

&emsp;&emsp;
The output is as follows:

```java
Try Block
Closing: 2
Closing: 1
Catch Block
Finally Block
```

&emsp;&emsp;
For the exam, make sure you understand why the method prints the statements in this
order. Remember, the resources are closed in the reverse of the order in which they are
declared, and the implicit **finally** is executed before the programmer-defined **finally**.

## III. Applying Effectively Final
While resources are often created in the try-with-resources statement, it is possible to declare
them ahead of time, provided they are marked **final** or effectively final. The syntax uses the
resource name in place of the resource declaration, separated by a semicolon `;`. Let’s try
another example:

```java
11: public static void main(String... xyz) {
12:     final var bookReader = new MyFileClass(4);
13:     MyFileClass movieReader = new MyFileClass(5);
14:     try (bookReader;
15:             var tvReader = new MyFileClass(6);
16:             movieReader) {
17:         System.out.println("Try Block");
18:     } finally {
19:         System.out.println("Finally Block");
20:     }
21: }
```

&emsp;&emsp;
Let’s take this one line at a time. Line 12 declares a **final** variable **bookReader**, while
line 13 declares an effectively final variable **movieReader**. Both of these resources can be
used in a try-with-resources statement. We know **movieReader** is effectively final because it
is a local variable that is assigned a value only once. Remember, the test for effectively final is
that if we insert the **final** keyword when the variable is declared, the code still compiles. <br />

&emsp;&emsp;
Lines 14 and 16 use the new syntax to declare resources in a try-with-resources statement,
using just the variable name and separating the resources with a semicolon `;`. Line 15 uses
the normal syntax for declaring a new resource within the **try** clause. <br />

&emsp;&emsp;
On execution, the code prints the following:

```java
Try Block
Closing: 5
Closing: 6
Closing: 4
Finally Block
```

&emsp;&emsp;
If you come across a question on the exam that uses a try-with-resources statement with a
variable not declared in the **try** clause, make sure it is effectively final. For example, the 
following does not compile:

```java
31: var writer = Files.newBufferedWriter(path);
32: try (writer) { // DOES NOT COMPILE
33:     writer.append("Welcome to the zoo!");
34: }
35: writer = null;
```

&emsp;&emsp;
The **writer** variable is reassigned on line 35, resulting in the compiler not considering
it effectively final. Since it is not an effectively final variable, it cannot be used in 
a try-with-resources statement on line 32. <br />

&emsp;&emsp;
The other place the exam might try to trick you is accessing a resource after it has been
closed. Consider the following:

```java
41: var writer = Files.newBufferedWriter(path);
42: writer.append("This write is permitted but a really bad idea!");
43: try (writer) {
44:     writer.append("Welcome to the zoo!");
45: }
46: writer.append("This write will fail!"); // IOException
```

&emsp;&emsp;
This code compiles but throws an exception on line 46 with the message **Stream
closed**. While it is possible to write to the resource before the try-with-resources statement,
it is not afterward.

## IV. Understanding Suppressed Exceptions
We conclude our discussion of exceptions with probably the most confusing topic: 
suppressed exceptions. What happens if the `close()` method throws an exception? Let’s try an
illustrative example:

```java
public class TurkeyCage implements AutoCloseable {
    public void close() {
        System.out.println("Close gate");
    }
    
    public static void main(String[] args) {
        try (var t = new TurkeyCage()) {
            System.out.println("Put turkeys in");
        }
    }
}
```

&emsp;&emsp;
If the **TurkeyCage** doesn’t close, the turkeys could all escape. Clearly, we need to handle
such a condition. We already know that the resources are closed before any programmer-coded 
**catch** blocks are run. This means we can catch the exception thrown by `close()` if
we want to. Alternatively, we can allow the caller to deal with it. <br />

&emsp;&emsp;
Let’s expand our example with a new **JammedTurkeyCage** implementation, shown here:

```java
1:  public class JammedTurkeyCage implements AutoCloseable {
2:      public void close() throws IllegalStateException {
3:          throw new IllegalStateException("Cage door does not close");
4:      }
5:      public static void main(String[] args) {
6:          try (JammedTurkeyCage t = new JammedTurkeyCage()) {
7:              System.out.println("Put turkeys in");
8:          } catch (IllegalStateException e) {
9:              System.out.println("Caught: " + e.getMessage());
10:         }
11:     }
12: }
```

&emsp;&emsp;
The `close()` method is automatically called by try-with-resources. It throws an
exception, which is caught by our catch block and prints the following:

```java
Caught: Cage door does not close
```

&emsp;&emsp;
This seems reasonable enough. What happens if the **try** block also throws an exception?
When multiple exceptions are thrown, all but the first are called _suppressed exceptions_. The
idea is that Java treats the first exception as the primary one and tacks on any that come up
while automatically closing. <br />

&emsp;&emsp;
What do you think the following implementation of our `main()` method outputs?

```java
5:  public static void main(String[] args) {
6:      try (JammedTurkeyCage t = new JammedTurkeyCage()) {
7:          throw new IllegalStateException("Turkeys ran off");
8:      } catch (IllegalStateException e) {
9:          System.out.println("Caught: " + e.getMessage());
10:         for (Throwable t: e.getSuppressed())
11:             System.out.println("Suppressed: "+t.getMessage());
12:     }
13: }
```

&emsp;&emsp;
Line 7 throws the primary exception. At this point, the **try** clause ends, and
Java automatically calls the `close()` method. Line 3 of **JammedTurkeyCage** throws an
**IllegalStateException**, which is added as a suppressed exception. Then line 8 catches
the primary exception. Line 9 prints the message for the primary exception. Lines 10 and
11 iterate through any suppressed exceptions and print them. The program prints the
following:

```java
Caught: Turkeys ran off
Suppressed: Cage door does not close
```

&emsp;&emsp;
Keep in mind that the catch block looks for matches on the primary exception. What do
you think this code prints?

```java
5:  public static void main(String[] args) {
6:      try (JammedTurkeyCage t = new JammedTurkeyCage()) {
7:          throw new RuntimeException("Turkeys ran off");
8:      } catch (IllegalStateException e) {
9:          System.out.println("caught: " + e.getMessage());
10:     }
11: }
```

&emsp;&emsp;
Line 7 again throws the primary exception. Java calls the `close()` method and adds a
suppressed exception. Line 8 would catch the **IllegalStateException**. However, we
don’t have one of those. The primary exception is a **RuntimeException**. Since this does
not match the catch clause, the exception is thrown to the caller. Eventually, the `main()`
method would output something like the following:

```java
Exception in thread "main" java.lang.RuntimeException: Turkeys ran off
    at JammedTurkeyCage.main(JammedTurkeyCage.java:7)
    Suppressed: java.lang.IllegalStateException:
            Cage door does not close
        at JammedTurkeyCage.close(JammedTurkeyCage.java:3)
        at JammedTurkeyCage.main(JammedTurkeyCage.java:8)
```

&emsp;&emsp;
Java remembers the suppressed exceptions that go with a primary exception even if we
don’t handle them in the code.

> #### Note
> If more than two resources throw an exception, the first one to be thrown
becomes the primary exception, and the rest are grouped as suppressed
exceptions. And since resources are closed in the reverse of the order
in which they are declared, the primary exception will be on the last
declared resource that throws an exception.

&emsp;&emsp;
Keep in mind that suppressed exceptions apply only to exceptions thrown in the try
clause. The following example does not throw a suppressed exception:

```java
5:  public static void main(String[] args) {
6:      try (JammedTurkeyCage t = new JammedTurkeyCage()) {
7:          throw new IllegalStateException("Turkeys ran off");
8:      } finally {
9:          throw new RuntimeException("and we couldn't find them");
10:     }
11: }
```

&emsp;&emsp;
Line 7 throws an exception. Then Java tries to close the resource and adds a suppressed
exception to it. Now we have a problem. The **finally** block runs after all this. Since line 9
also throws an exception, the previous exception from line 7 is lost, with the code printing
the following:

```java
Exception in thread "main" java.lang.RuntimeException:
    and we couldn't find them
    at JammedTurkeyCage.main(JammedTurkeyCage.java:9)
```

&emsp;&emsp;
This has always been and continues to be bad programming practice. We don’t want to lose
exceptions! Although out of scope for the exam, the reason for this has to do with backward
compatibility. This behavior existed before automatic resource management was added.
